/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.12 public/models/fishBread.glb
Author: Yeon2 (https://sketchfab.com/hJyJin)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fish-shaped-bun-eb3c1649f5ad4fc7af7a4de093533d9f
Title: fish_shaped_bun
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Bbang(props) {
  const { nodes, materials } = useGLTF('/models/fishBread.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['fish_shaped_bun_01_-_Default_0'].geometry} material={materials['01_-_Default']} rotation={[Math.PI, 0, -Math.PI]} />
    </group>
  )
}

useGLTF.preload('/models/fishBread.glb')
