/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.12 public/models/hwatuCard.glb
Author: haruhic192 (https://sketchfab.com/haruhic192)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hwatu-card-sakura-402e35aa2908480596a374586c551145
Title: hwatu card, sakura
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Hwatu(props) {
  const { nodes, materials } = useGLTF('/models/hwatuCard.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={10}>
        <group position={[0, 1.04, 0]}>
          <mesh geometry={nodes['card002_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[0, 0, 0.03]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/hwatuCard.glb')
