/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.12 public/models/koreanTotem/scene.gltf
Author: mingizz0011 (https://sketchfab.com/mingizz0011)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/korean-traditional-totem-dbf99e21f3304905b0e04b1e9f732abc
Title: 웃음장승 korean traditional totem
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function KoreanTotem(props) {
  const { nodes, materials } = useGLTF('/models/koreanTotem/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['������������_������������_0'].geometry} material={materials.material} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/models/koreanTotem/scene.gltf')
