/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.12 public/models/koreanDrum.glb
Author: Korea Culture Information Service Agency (https://sketchfab.com/kcisameta)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/kcisa-gyobang-drum-1-1-6cbd86faf4b1499182b24dfe7268488a
Title: KCISA-Gyobang Drum_1(교방고_1)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function KoreanDrum(props) {
  const { nodes, materials } = useGLTF('/models/koreanDrum.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Gyobang-Body_LowRes_Item2-2_GyobangDrum_LowRes_0'].geometry} material={materials['Item2-2_GyobangDrum_LowRes']} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/models/koreanDrum.glb')
